title: Brunaugh Lab
description: >-
  We study transport in complex, dynamic environments and engineer therapeutic
  interventions across barriers, particles, and respiratory systems.
url: "https://brunaughlab.com"
baseurl: ""

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-seo-tag
